name: "Build workflow"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-20.04
    container: python:${{ matrix.python }}
    strategy:
      matrix:
        python: ["3.10"]
    steps:
      - run: python3 --version
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Clone Algorand Sanbox
        run: cd .. && git clone https://github.com/algorand/sandbox.git

      - name: Run Algorand Sandbox
        shell: 'script -q -e -c "bash {0}"' # hacky hack to make TTY work
        run: cd ../sandbox && ./sandbox up dev -v

      - name: Delay before testing
        run: sleep 60

      - name: Install python dependencies
        run: make setup-development

      - name: Tests
        run: make all-tests

      - name: Stop running images
        run: make sandbox-dev-stop
